Repository Alfresco/alfresco-dbp-deployment, pull requests merged in 2020-04, with the labels that each got.

#159 Update to APS 0.2.1 helm chart
  helm/alfresco-dbp/requirements.yaml
Labels: PR: reviewed-approved

#160 ACS-54: Identity Services Testing
  helm/alfresco-dbp/requirements.yaml
Labels: PR: partially-approved

#161 ACS-54: Changed all instances of 6.2.0 to 6.2.1-RC3
  README.md
  docker/repository/Dockerfile
  docker/repository/build.properties
  docker/share/Dockerfile
  docker/share/build.properties
  helm/alfresco-dbp/values.yaml
  test/postman/dbp-test-collection.json
Labels: PR: reviewed-approved

#162 Changed alfresco-share version to 6.2.0-RC2
  README.md
  docker/share/Dockerfile
  docker/share/build.properties
  helm/alfresco-dbp/values.yaml
  test/postman/dbp-test-collection.json
Labels: PR: unreviewed
